<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="7" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-03T13:18:32 GMT-04:00" name="Suite" finished-at="2025-04-03T13:18:59 GMT-04:00" duration-ms="26283">
    <groups>
      <group name="ErrorHandle">
        <method signature="ErrorValidations.LoginErrorValidation()[pri:0, instance:tests.ErrorValidations@487db668]" name="LoginErrorValidation" class="tests.ErrorValidations"/>
      </group> <!-- ErrorHandle -->
      <group name="Purchase">
        <method signature="StandAlone.SubmitOrder(java.util.HashMap)[pri:0, instance:tests.StandAlone@3a4621bd]" name="SubmitOrder" class="tests.StandAlone"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2025-04-03T13:18:32 GMT-04:00" name="ExceptionHandling" finished-at="2025-04-03T13:18:51 GMT-04:00" duration-ms="18837">
      <class name="tests.ErrorValidations">
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:tests.ErrorValidations@487db668]" started-at="2025-04-03T13:18:32 GMT-04:00" name="LaunchApplication" finished-at="2025-04-03T13:18:38 GMT-04:00" duration-ms="5973" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:tests.ErrorValidations@487db668]" started-at="2025-04-03T13:18:38 GMT-04:00" name="LoginErrorValidation" finished-at="2025-04-03T13:18:39 GMT-04:00" duration-ms="567" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email  password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email  password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at tests.ErrorValidations.LoginErrorValidation(ErrorValidations.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:tests.ErrorValidations@487db668]" started-at="2025-04-03T13:18:39 GMT-04:00" name="teardown" finished-at="2025-04-03T13:18:39 GMT-04:00" duration-ms="99" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:tests.ErrorValidations@487db668]" started-at="2025-04-03T13:18:39 GMT-04:00" name="LaunchApplication" finished-at="2025-04-03T13:18:43 GMT-04:00" duration-ms="3814" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:tests.ErrorValidations@487db668]" started-at="2025-04-03T13:18:43 GMT-04:00" name="LoginErrorValidation" finished-at="2025-04-03T13:18:44 GMT-04:00" duration-ms="1232" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email  password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email  password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at tests.ErrorValidations.LoginErrorValidation(ErrorValidations.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:tests.ErrorValidations@487db668]" started-at="2025-04-03T13:18:44 GMT-04:00" name="teardown" finished-at="2025-04-03T13:18:45 GMT-04:00" duration-ms="113" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:tests.ErrorValidations@487db668]" started-at="2025-04-03T13:18:45 GMT-04:00" name="LaunchApplication" finished-at="2025-04-03T13:18:48 GMT-04:00" duration-ms="3719" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:tests.ErrorValidations@487db668]" started-at="2025-04-03T13:18:48 GMT-04:00" name="ProductErrorValidation" finished-at="2025-04-03T13:18:51 GMT-04:00" duration-ms="2820" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:tests.ErrorValidations@487db668]" started-at="2025-04-03T13:18:51 GMT-04:00" name="teardown" finished-at="2025-04-03T13:18:51 GMT-04:00" duration-ms="112" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- tests.ErrorValidations -->
    </test> <!-- ExceptionHandling -->
    <test started-at="2025-04-03T13:18:32 GMT-04:00" name="SubmitOrder" finished-at="2025-04-03T13:18:59 GMT-04:00" duration-ms="26283">
      <class name="tests.StandAlone">
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:tests.StandAlone@3a4621bd]" started-at="2025-04-03T13:18:32 GMT-04:00" name="LaunchApplication" finished-at="2025-04-03T13:18:38 GMT-04:00" duration-ms="5892" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:tests.StandAlone@3a4621bd]" started-at="2025-04-03T13:18:38 GMT-04:00" name="SubmitOrder" data-provider="getData" finished-at="2025-04-03T13:18:42 GMT-04:00" duration-ms="3658" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sivin@0906, product=ZARA COAT 3, email=gorre.sivaprasad@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:tests.StandAlone@3a4621bd]" started-at="2025-04-03T13:18:42 GMT-04:00" name="teardown" finished-at="2025-04-03T13:18:42 GMT-04:00" duration-ms="82" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:tests.StandAlone@3a4621bd]" started-at="2025-04-03T13:18:42 GMT-04:00" name="LaunchApplication" finished-at="2025-04-03T13:18:46 GMT-04:00" duration-ms="4029" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:tests.StandAlone@3a4621bd]" started-at="2025-04-03T13:18:46 GMT-04:00" name="SubmitOrder" data-provider="getData" finished-at="2025-04-03T13:18:50 GMT-04:00" duration-ms="3742" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sivin@0906, product=IPHONE 13 PRO, email=vinneith@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:tests.StandAlone@3a4621bd]" started-at="2025-04-03T13:18:50 GMT-04:00" name="teardown" finished-at="2025-04-03T13:18:50 GMT-04:00" duration-ms="117" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:tests.StandAlone@3a4621bd]" started-at="2025-04-03T13:18:50 GMT-04:00" name="LaunchApplication" finished-at="2025-04-03T13:18:54 GMT-04:00" duration-ms="3779" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="submittwo()[pri:0, instance:tests.StandAlone@3a4621bd]" started-at="2025-04-03T13:18:54 GMT-04:00" name="submittwo" finished-at="2025-04-03T13:18:54 GMT-04:00" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submittwo -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:tests.StandAlone@3a4621bd]" started-at="2025-04-03T13:18:54 GMT-04:00" name="teardown" finished-at="2025-04-03T13:18:54 GMT-04:00" duration-ms="73" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:tests.StandAlone@3a4621bd]" started-at="2025-04-03T13:18:54 GMT-04:00" name="LaunchApplication" finished-at="2025-04-03T13:18:58 GMT-04:00" duration-ms="3723" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:tests.StandAlone@3a4621bd]" started-at="2025-04-03T13:18:58 GMT-04:00" name="OrderHistoryTest" finished-at="2025-04-03T13:18:58 GMT-04:00" depends-on-methods="tests.StandAlone.SubmitOrder" duration-ms="890" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at tests.StandAlone.OrderHistoryTest(StandAlone.java:61)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:tests.StandAlone@3a4621bd]" started-at="2025-04-03T13:18:59 GMT-04:00" name="teardown" finished-at="2025-04-03T13:18:59 GMT-04:00" duration-ms="108" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- tests.StandAlone -->
    </test> <!-- SubmitOrder -->
  </suite> <!-- Suite -->
</testng-results>
